M48
; DRILL file {KiCad 9.0.7} date 2026-04-12T11:49:31+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-12T11:49:31+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X106.8Y-58.525
X106.8Y-80.925
T2
X72.0Y-51.0
X93.5Y-147.5
X209.0Y-51.5
X209.0Y-147.0
M30
